---
- name: Installing andrewrothstein.userful_groups
  ansible.builtin.include_role:
    name: andrewrothstein.useful_groups
- name: Creating users
  become: true
  become_user: root
  with_items: '{{ users }}'
  ansible.builtin.user:
    state: present
    name: '{{ item.n }}'
    shell: '{{ item.s }}'
    append: true
    groups: '{{ item.g }}'

- name: Creating ssh dirs
  become: true
  become_user: root
  with_items: '{{ users }}'
  ansible.builtin.file:
    state: directory
    path: '{{ home_prefix }}/{{ item.n }}/.ssh'
    mode: '700'
    owner: '{{ item.n }}'

- name: Installing authorized keys
  become: true
  become_user: root
  with_items: '{{ users }}'
  ansible.builtin.copy:
    src: home/{{ item.n }}/.ssh/authorized_keys
    dest: '{{ home_prefix }}/{{ item.n }}/.ssh/authorized_keys'
    owner: '{{ item.n }}'
    mode: '{{ item.m | default("600") }}'
