---
- include_role:
    name: andrewrothstein.useful-groups
- name: create users
  become: true
  become_user: root
  with_items: '{{ users }}'
  user:
    state: present
    name: '{{ item.n }}'
    shell: '{{ item.s }}'
    append: true
    groups: '{{ item.g }}'

- name: creating ssh dirs
  become: true
  become_user: root
  with_items: '{{ users }}'
  file:
    state: directory
    path: '{{ home_prefix }}/{{ item.n }}/.ssh'
    mode: 0700
    owner: '{{ item.n }}'

- name: installing authorized keys
  become: true
  become_user: root
  with_items: '{{ users }}'
  copy:
    src: home/{{ item.n }}/.ssh/authorized_keys
    dest: '{{ home_prefix }}/{{ item.n }}/.ssh/authorized_keys'
    owner: '{{ item.n }}'
    mode: '{{ item.m | default("0600") }}'
